### ISSUE TITLE
Imgur image posting error 400?

### ISSUE THREAD

**Issue by RikerW** [The-Quill/SE-Chat-Oneboxer#38]
At random times Chrome on OS X will alert me `Error posting old image to imgur. Server status 400`.

I don't see any repercussions of this. But the error could stop?

**Comment by The-Quill** [comment]
@RikerW what chrome version are you using and can you screenshot this?

**Comment by RikerW** [comment]
Chrome 50.  Traceback:

http://i.stack.imgur.com/kJPAo.png

I'll screenshot the alert next time I see it.

**Comment by RikerW** [comment]
http://imgur.com/VBmHJTT

**Comment by The-Quill** [comment]
I think this is a config issue.... I need to do some better error handling though

**Comment by RikerW** [comment]
@The-Quill hows it going? >_>

**Comment by RikerW** [comment]
@The-Quill  how's it going now? >_>

**Comment by The-Quill** [comment]
This issue feels like an update issue, and considering I never actully use any image uploading code, I'm gonna close this as no-repro

**Comment by vihanb** [comment]
@The-Quill if you don't want to fix it you can always post this image:

https://camo.githubusercontent.com/d58c5fc5c80f05d4d4d7ada765b4786a9b77c812/687474703a2f2f692e696d67666c69702e636f6d2f31306f3034322e6a7067

**Comment by The-Quill** [comment]
@vihanb It's not that I don't want to fix it, I just generally can't fix it, or I can't reproduce it enough to fix it myelf
