### ISSUE TITLE
Make the onebox appear beneath the link

### ISSUE THREAD

**Issue by RikerW** [The-Quill/SE-Chat-Oneboxer#40]
Maybe have the onebox appear beneath the message? i.e. append the image/box to the end of the message. Note this would also solve [this issue](https://github.com/The-Quill/SE-Chat-Oneboxer/issues/39) (Only onebox if the link is the only message content)

**Comment by RikerW** [comment]
status? It's pretty annoying.

**Comment by The-Quill** [comment]
Fixed in 385aa83
